baseurl: /s9c9-ilp-test

collections:
  learners:
    output: true

defaults:
  - scope:
      path: ""
      type: "learners"
    values:
      layout: "learner"
  - scope:
      path: ""
    values:
      layout: "default"