backend:
  name: github
  repo: aeone/s9c9-ilp-test
  branch: master
  site_domain: infallible-euclid-eeb3b0.netlify.com
media_folder: 'assets/uploads'
collections:
  - name: 'learner'
    label: 'Learner'
    folder: '_learners/'
    create: true
    slug: '{{year}}{{month}}-{{cohort}}-{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - label: 'Cohort'
        name: 'cohort'
        widget: "relation"
        collection: "cohort"
        searchFields: ["name", "code"]
        valueField: "code"
        displayFields: ["name"]
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Phone', name: 'phone', widget: 'string' }
      - { label: 'ULN', name: 'uln', widget: 'string' }
      - label: 'Line Manager'
        name: 'line-manager'
        widget: 'object'
        fields: 
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
      - label: 'Entries'
        name: 'ilp-entries'
        widget: 'list'
        fields:
         - { label: 'Title', name: 'title', widget: 'string' }
         - { label: 'Date', name: 'date', widget: 'datetime', timeFormat: false }
         - { label: 'Type', name: 'type', widget: 'select', options: ['milestone', 'guidance'] }
         - { label: 'Flag', name: 'flag', widget: 'string' }
         - { label: 'Flag Value', name: 'flag-value', widget: 'select', options: ['incomplete', 'in_progress', 'complete'] }
         - { label: 'Description', name: 'description', widget: 'markdown' }
  - name: 'cohort'
    label: 'Cohort'
    folder: '_cohorts/'
    create: true
    slug: '{{code}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Cohort Shortcode', name: 'code', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - label: 'Course'
        name: 'course'
        widget: "relation"
        collection: "course"
        searchFields: ["name", "code"]
        valueField: "code"
        displayFields: ["name"]
  - name: 'course'
    label: 'Course'
    folder: '_courses/'
    create: true
    slug: '{{code}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Course Shortcode', name: 'code', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - label: 'Progress Flags'
        name: 'flags'
        widget: 'list'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Flag Shortcode', name: 'code', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }