backend:
  name: github
  repo: aeone/s9c9-ilp-test
  branch: master
  site_domain: infallible-euclid-eeb3b0.netlify.com
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }