backend:
  name: github
  repo: aeone/s9c9-ilp-test
  branch: master
  site_domain: infallible-euclid-eeb3b0.netlify.com
media_folder: 'assets/uploads'
collections:
  - name: 'learner'
    label: 'Learner'
    folder: '_learners/'
    create: true
    slug: '{{year}}{{month}}-{{cohort}}-{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Cohort Shortcode', name: 'cohort', widget: 'string' }
      - label: 'Entries'
        name: 'ilp-entries'
        widget: 'list'
        fields:
         - { label: 'Title', name: 'title', widget: 'string' }
         - { label: 'Date', name: 'date', widget: 'datetime' }
         - { label: 'Type', name: 'type', widget: 'select', options: ['milestone', 'guidance'] }
         - { label: 'Flag', name: 'flag', widget: 'string' }
         - { label: 'Flag Value', name: 'flag-value', widget: 'select', options: ['incomplete', 'in_progress', 'complete'] }
         - { label: 'Description', name: 'description', widget: 'markdown' }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - name: 'cohort'
        label: 'Cohorts'
        file: '_data/cohorts.yml'
        fields:
          - label: 'List of cohorts'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Code', name: 'code', widget: 'string' }
              - { label: 'Course', name: 'course', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
      - name: 'course'
        label: 'Courses'
        file: '_data/courses.yml'
        fields:
          - label: 'List of courses'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Code', name: 'code', widget: 'string' }
              - label: 'Flags'
                name: 'flags'
                widget: 'list'
                fields:
                 - { label: 'Name', name: 'name', widget: 'string' }
                 - { label: 'Code', name: 'code', widget: 'string' }
                 - { label: 'Description', name: 'description', widget: 'string' }
              