backend:
  name: github
  repo: aeone/s9c9-ilp-test
  branch: master
  site_domain: infallible-euclid-eeb3b0.netlify.com
media_folder: 'assets/uploads'
collections:
  - name: 'learner'
    label: 'Learner'
    folder: '_learners/'
    create: true
    slug: '{{year}}{{month}}-{{cohort}}-{{name}}'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Cohort', name: 'cohort', widget: 'relation', collection: 'cohort', displayFields: ['name'], searchFields: ['name'], valueField: ['code'] }
      - label: 'Entries'
        name: 'ilp-entries'
        widget: 'list'
        fields:
         - { label: 'Date', name: 'date', widget: 'datetime' }
         - { label: 'Type', name: 'type', widget: 'select', options: ['milestone', 'guidance'] }
         - { label: 'Flag', name: 'flag', widget: 'string' }
         - { label: 'Title', name: 'title', widget: 'string' }
         - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'cohort'
    label: 'Cohorts'
    file: '_data/cohorts.yml'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Code', name: 'code', widget: 'string' }
      - { label: 'Course', name: 'course', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }